@id=64248136a32abf0bfa1420a2
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI0ODEzNmEzMmFiZjBiZmExNDIwYTIiLCJmaXJzdG5hbWUiOiJBbGVqYW5kcm8iLCJsYXN0bmFtZSI6IkdvbWV6IE5pZXRvIiwiYWdlIjozOSwiZW1haWwiOiJhbGVqYW5kcm9AbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR2MWdSYjRIU1ZlMWN4NU8uT2R3eGtlYnpZYmZBelRwN3AvNUc4WFBVR0ZOcmcvNlNqbEVhRyIsInJvbGUiOiJBZG1pbiIsIl9fdiI6MCwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgwNzI2NDkyLCJleHAiOjE2ODA3MzAwOTJ9.-kUAQdTpouFTO5F3RBZoswr4DCvtJLOc3VNGLTA19zY

GET http://localhost:8080/api/users/{{id}}
Authorization: Bearer {{token}}