@id=64248136a32abf0bfa1420a2
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjQ4MTM2YTMyYWJmMGJmYTE0MjBhMiIsImZpcnN0bmFtZSI6IkFsZWphbmRybyIsImxhc3RuYW1lIjoiR29tZXogTmlldG8iLCJlbWFpbCI6ImFsZWphbmRyb0BtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzQWRtaW4iOnRydWUsImNhcnRJZCI6IjY0NDQ2NjdjY2RjY2MyNTc5ZmZhMDY4YiIsImlhdCI6MTY4MjI1MzkzMiwiZXhwIjoxNjgyMjU3NTMyfQ.C70Z2iodIkgo_szYs7Ou0UVaFzeuwixbGQBmMA0rTAs

GET http://localhost:8080/api/users/{{id}}
Authorization: Bearer {{token}}