@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI0ODEzNmEzMmFiZjBiZmExNDIwYTIiLCJmaXJzdG5hbWUiOiJBbGVqYW5kcm8iLCJsYXN0bmFtZSI6IkdvbWV6IE5pZXRvIiwiYWdlIjozOSwiZW1haWwiOiJhbGVqYW5kcm9AbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR2MWdSYjRIU1ZlMWN4NU8uT2R3eGtlYnpZYmZBelRwN3AvNUc4WFBVR0ZOcmcvNlNqbEVhRyIsInJvbGUiOiJBZG1pbiIsIl9fdiI6MCwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgwNzI0NDE5LCJleHAiOjE2ODA3MjgwMTl9.Fbigvf7jghCeWNd7NfYfUFXl7wsVbtRTDrYIGYbjy6M

POST http://localhost:8080/api/carts
Authorization: Bearer {{token}}