@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjQ4MTM2YTMyYWJmMGJmYTE0MjBhMiIsImZpcnN0bmFtZSI6IkFsZWphbmRybyIsImxhc3RuYW1lIjoiR29tZXogTmlldG8iLCJlbWFpbCI6ImFsZWphbmRyb0BtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzQWRtaW4iOnRydWUsImNhcnRJZCI6bnVsbCwiaWF0IjoxNjgyMzU3NDAxLCJleHAiOjE2ODIzNjEwMDF9.2BE3_qpUZuiGGqGtyZSfwnmMxid79oR6BkqBPCzLRdE

POST http://localhost:8080/api/products/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Producto 18",
    "description": "Producto 18",
    "price": 300,
    "thumbnail": "https://picsum.photos/200/300",
    "code": 18,
    "stock": 120,
    "category": "categoria",
    "status": true
}

# [
#   {
#     "title": "Producto 13",
#     "description": "Producto 13",
#     "price": 300,
#     "thumbnail": "https://picsum.photos/200/300",
#     "code": 13,
#     "stock": 100,
#     "category": "categoria",
#     "status": true
#   },
#   {
#     "title": "Producto 14",
#     "description": "Producto 14",
#     "price": 300,
#     "thumbnail": ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
#     "code": 14,
#     "stock": 100,
#     "category": "categoria",
#     "status": true
#   }
# ]
